### ISSUE TITLE
certbot renew --dry-run fails 

### ISSUE THREAD

**Issue by jcoker85** [acme-dns/acme-dns-client#8]
After performing the steps on the readme, and running 

`acme-dns-client check -d DOMAIN`

I get the following output

```
Checking acme-dns configuration for domain DOMAIN
 [*] Registered acme-dns account found!
 [*] CNAME record found and set up correctly!
 [*] CAA record found!
 [*] CAA AccountURI found!
```

I attempted to do a dry run of the renewal using

`certbot renew --dry-run`

But always receive the message

```
1 renew failure(s), 0 parse failure(s)

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: DOMAIN
   Type:   None
   Detail: CAA record for DOMAIN prevents issuance
```

My CAA record is as follows: 

```
DOMAIN  CAA  0 issue "letsencrypt.org; validationmethods=dns-01; accounturi=https://acme-v02.api.letsencrypt.org/acme/acct/ACCT_NUM"
```

Am I missing a step in the renewal process?

**Comment by joohoi** [comment]
Hi, there are multiple things that can be at play here, but I would assume that a certificate for `DOMAIN` was initially using some other validation method (http-01 most likely). `certbot renew`, even with `--dry-run` will just reuse the initial certbot configuration and tries to renew the certificate using those. 

Now you have added a `CAA` record that only allows DNS validation, that causes the renewal to fail.

**Comment by jcoker85** [comment]
Hi @joohoi,

Thanks so much for your response, and apologies in the delay in mine. 

I did get this working by performing:

`sudo apt purge certbot` followed by `sudo apt autoremove` (not sure second step is entirely necessary)

and rerunning all of the steps listed in the README. So, it looks like your assumption was correct that old Certbot configuration was causing some confusion during the renewal process. 

Thanks again!
